### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Priyanshu2631**
Corrected some spelling mistakes alongwith putting appropriate markups in the solution section thus structuring it. Kindly review it, resolving issue #8

### CODE REVIEW

**Comment by gitgoap** [comment]
@Priyanshu2631 
Please remove image at line 108
and commit again

logo

**Comment by gitgoap** [comment]
Any updates @Priyanshu2631

**Comment by Priyanshu2631** [comment]
@gitgoap I hv removed that image,kindly check

**Review by gitgoap — APPROVED** [review]

**Comment by gitgoap** [comment]
Looks good

**Review by gitgoap — APPROVED** [review]

**Pull request merged**
