### PR TITLE
Added contributors image list

### LINKED ISSUE #17: Adding list of contributors image under readme
Add this thing after the future scope/ feature section

### PR DESCRIPTION
**Pull request by Arpcoder**
This closes #17

### CODE REVIEW

**Comment by gitgoap** [comment]
@Arpcoder 
Good work

**Comment by Arpcoder** [comment]
> @Arpcoder Good work

So please merge this.. Also add ssoc labels

**Comment by gitgoap** [comment]
@Arpcoder 

Your PR is [8 commits behind] please update the branch with new commits or raise another PR containing this contributor section in readme an

**Comment by Arpcoder** [comment]
> @Arpcoder
> 
> Your repo is [8 commits behind] please update the branch with new commits recently added, other wise this would give rise to branch conflicts. or raise another PR containing this feature: 'contributor section in the readme' with updated branch.

Updated the branch

**Review by gitgoap — APPROVED** [review]

**Pull request merged**
